import selenium
from selenium import webdriver
import time
from datetime import datetime, timedelta
import os
import smtplib


chrome_options = webdriver.ChromeOptions()
chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)


# Now you can start using Selenium
while(True):
  WeLogin():
  SendMail():

  
 
  
  # Wasting time 1728*100 = 48 hours
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)

#driver.quit()
